/** UI */
#import "UIScreen+JCScreen.h"
#import "UITabBarController+JCTabBarController.h"
#import "UINavigationController+JCNavigationAttributes.h"
#import "UIBarButtonItem+JCBlock.h"
#import "UIScrollView+JCScrollView.h"
#import "UIGestureRecognizer+JCBlock.h"
#import "UITableViewCell+JCSeparator.h"
#import "UIApplication+JCApplication.h"
#import "UIButton+JCButton.h"
#import "UIColor+JCColor.h"
#import "UIColor+JCSeries.h"
#import "UIControl+JCControl.h"
#import "UIDevice+JCDevice.h"
#import "UIFont+JCScale.h"
#import "JCFontName.h"
#import "UIImage+JCImage.h"
#import "UITextField+JCTextField.h"
#import "CALayer+JCLayer.h"
#import "JCGraphicsUtilities.h"
#import "UIView+JCView.h"
#import "UIWebView+JCJavaScript.h"
#import "UIWebView+JCHTML.h"
#import "UIBezierPath+JCBezierPath.h"
#import "UILabel+JCLabel.h"
#import "UINavigationItem+JCLoading.h"
#import "UITableView+JCPlaceholder.h"
#import "UIBarItem+JCBarItem.h"
#import "UIViewController+JCViewController.h"
#import "CADisplayLink+JCToRunLoop.h"
#import "UIWebView+JCProgress.h"

/** NS */
#import "NSBundle+JCBundle.h"
#import "NSURL+JCURL.h"
#import "NSFileManager+JCFileManager.h"
#import "NSArray+JCBlock.h"
#import "NSData+JCData.h"
#import "NSDate+JCDate.h"
#import "NSDictionary+JCBlock.h"
#import "NSException+JCException.h"
#import "NSNumber+JCNumber.h"
#import "NSObject+JCObject.h"
#import "NSString+JCString.h"
#import "NSTimer+JCBlock.h"
#import "NSMutableAttributedString+JCAttributedString.h"

FOUNDATION_EXPORT double JCCategoryKitVersionNumber;
FOUNDATION_EXPORT const unsigned char JCCategoryKitVersionString[];